name: Push Event Workflow

on:
  push:
    branches:
      - '**'  # This triggers on push to any branch

jobs:
  run-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Node.js (example, can be Python or other)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests (replace with your project's test command)
        run: npm test

      - name: Build the project (optional)
        run: npm run build
